// auth related
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOG_OUT = 'AUTH_LOG_OUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
// reset app state
export const RESET_APP_STATE = 'RESET_APP_STATE';

// ingredients related
export const SET_INGREDIANTS = 'SET_INGREDIANTS';
export const FETCH_INGREDIANTS_FAILED = 'FETCH_INGREDIANTS_FAILED';
export const ADD_INGREDIANT = 'ADD_INGREDIANT';
export const REMOVE_INGREDIANT = 'REMOVE_INGREDIANT';
export const RESET_INGREDIANTS = 'RESET_INGREDIANTS';

// orders related
export const FETCH_ORDERS_INIT = 'FETCH_ORDERS_INIT';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';

export const ORDER_INITATE = 'ORDER_INITATE';
export const ORDER_INIT = 'ORDER_INIT';
export const ORDER_SUCCESS = 'ORDER_SUCCESS';
export const ORDER_FAILED = 'ORDER_FAILED';

export const DELETE_ORDERS_INIT = 'DELETE_ORDERS_INIT';
export const DELETE_ORDERS_SUCCESS = 'DELETE_ORDERS_SUCCESS';
export const DELETE_ORDERS_FAILED = 'DELETE_ORDERS_FAILED';

